# Generated by Django 4.0.2 on 2022-10-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
